### ISSUE TITLE
About

### ISSUE THREAD

**Issue by Ontheroad123** [yizhiwang96/Slice3D#1]
Hello, this is a meaningful work, i'm interested in it, could you please provied code, thanks.

**Comment by yizhiwang96** [comment]
Thank you for your interest! I plan to release the code and demo in the next week.

**Comment by yizhiwang96** [comment]
@Ontheroad123 Sorry for the delay since our servers are experiencing a breakdown. We will let you know once the code and pretrained models are ready.

**Comment by yizhiwang96** [comment]
@Ontheroad123 Thanks for your patience. The code has now been released except the pretrained checkpoints of generation-based slicing. We are now training it and will update in the [Onedrive link](https://onedrive.live.com/?authkey=%21AFAtidJ6MB%2DF3jk&id=A0004126AB48D040%21104163&cid=A0004126AB48D040) as soon as possible.

**Comment by Ontheroad123** [comment]
> @Ontheroad123 Thanks for your patience. The code has now been released except the pretrained checkpoints of generation-based slicing. We are now training it and will update in the [Onedrive link](https://onedrive.live.com/?authkey=%21AFAtidJ6MB%2DF3jk&id=A0004126AB48D040%21104163&cid=A0004126AB48D040) as soon as possible.

Thank you very much.
