### ISSUE TITLE
Missing occ_pred key

### ISSUE THREAD

**Issue by 111sadas** [yizhiwang96/Slice3D#3]
Great work! When I tried to train the Slice3D network using our dataset, I changed the parameter "pred_type" to "occ" and found that the network framework lacked the "occ_pred" output. How should I operate to implement the 'occ' method of training?

**Comment by yizhiwang96** [comment]
Hi @111sadas, thank you for interest in our paper! To support occupancy output, you can add modify [self.fc_out](https://github.com/yizhiwang96/Slice3D/blob/d02c0b307c94eb113feb3a5d4f6543cfdaad4dbb/reg_slices/src/models.py#L22) to a linear layer and a sigmoid function which outputs a value between 0 - 1, then, use cross entropy loss ([example](https://github.com/yizhiwang96/ARO-Net/blob/3c0cebc2888bfffd3604979a3bc4c36556ad1fd4/train.py#L28)) to train the occ prediction.
