### ISSUE TITLE
About ShapeNet Slicing

### ISSUE THREAD

**Issue by fei1lee** [yizhiwang96/Slice3D#4]
Great work! I am looking to engage in joint training on the multi-category ShapeNet dataset, which includes 13 distinct categories. Could you please share the code for slicing the ShapeNet dataset?

**Comment by yizhiwang96** [comment]
Thank you for your interest! I'm busy with another project so I'm unable to provide a clean code to you right now. But it is very easy to adapt the scripts in `render_slices/` to work for shapenet! There will be two key changes: (1) change [`bpy.ops.import_scene.gltf`](https://github.com/yizhiwang96/Slice3D/blob/d02c0b307c94eb113feb3a5d4f6543cfdaad4dbb/render_slices/blender_script_slices.py#L157) ([another place](https://github.com/yizhiwang96/Slice3D/blob/d02c0b307c94eb113feb3a5d4f6543cfdaad4dbb/render_slices/blender_script_input.py#L140)) to `bpy.ops.import_scene.obj` (2) use axis aligned slicing: [`--slice_direction`](https://github.com/yizhiwang96/Slice3D/blob/d02c0b307c94eb113feb3a5d4f6543cfdaad4dbb/render_slices/gen_slices.py#L31C35-L31C41) set to `axis`.

**Comment by fei1lee** [comment]
> Thank you for your interest! I'm busy with another project so I'm unable to provide a clean code to you right now. But it is very easy to adapt the scripts in to work for shapenet! There will be two key changes: (1) change [`bpy.ops.import_scene.gltf`](https://github.com/yizhiwang96/Slice3D/blob/d02c0b307c94eb113feb3a5d4f6543cfdaad4dbb/render_slices/blender_script_slices.py#L157) ([anothe place](https://github.com/yizhiwang96/Slice3D/blob/d02c0b307c94eb113feb3a5d4f6543cfdaad4dbb/render_slices/blender_script_input.py#L140)) to (2) use axis aligned slicing: [`--slice_direction`](https://github.com/yizhiwang96/Slice3D/blob/d02c0b307c94eb113feb3a5d4f6543cfdaad4dbb/render_slices/blender_script_slices.py#L34) set to .`render_slices/``bpy.ops.import_scene.obj``axis`

Thank you very much for your help! I have successfully generated the input images and slice image pairs.

**Comment by ChongminWang** [comment]
> > Thank you for your interest! I'm busy with another project so I'm unable to provide a clean code to you right now. But it is very easy to adapt the scripts in to work for shapenet! There will be two key changes: (1) change [`bpy.ops.import_scene.gltf`](https://github.com/yizhiwang96/Slice3D/blob/d02c0b307c94eb113feb3a5d4f6543cfdaad4dbb/render_slices/blender_script_slices.py#L157) ([anothe place](https://github.com/yizhiwang96/Slice3D/blob/d02c0b307c94eb113feb3a5d4f6543cfdaad4dbb/render_slices/blender_script_input.py#L140)) to (2) use axis aligned slicing: [`--slice_direction`](https://github.com/yizhiwang96/Slice3D/blob/d02c0b307c94eb113feb3a5d4f6543cfdaad4dbb/render_slices/blender_script_slices.py#L34) set to .`` render_slices/``bpy.ops.import_scene.obj``axis ``
> 
> Thank you very much for your help! I have successfully generated the input images and slice image pairs.

I'm very sorry to open this issue. I was confused when I processed shapenet data. Can you share the gen_input.py and gen_slices.py scripts that handle shapnet slice?

In fact, my biggest puzzle is how do you handle shapnet's 13 categories to generate similar "... /data/objaverse/input_models_path-lvis.json "json file.
